### ISSUE TITLE
IllegalArgumentsException: Empty Storage ID

### ISSUE THREAD

**Issue by Shashank066** [anggrayudi/SimpleStorage#116]
FileFullPath.kt line 115 
```

Fatal Exception: java.lang.IllegalArgumentException: Empty storage ID
       at com.anggrayudi.storage.file.FileFullPath.checkIfStorageIdIsAccessibleInSafSelector(FileFullPath.kt:115)
       at com.anggrayudi.storage.SimpleStorage.requestStorageAccess(SimpleStorage.kt:156)
       at com.anggrayudi.storage.SimpleStorageHelper.requestStorageAccess(SimpleStorageHelper.kt:353)
       at com.anggrayudi.storage.SimpleStorageHelper.requestStorageAccess$default(SimpleStorageHelper.kt:345)
       at com.anggrayudi.storage.SimpleStorageHelper.requestStorageAccess(SimpleStorageHelper.kt:8)
```

One of the user is getting this crash on Android 9. The Storage is located on SD card.

**Comment by anggrayudi** [comment]
Probably this is because the user uses `:` special character in his file/folder. Maybe I need to replace the current logic from substring the SD card ID to regex extraction for more accurate results.

**Comment by Shashank066** [comment]
If any additional logging can be helpful, I can ask the user for installing custom apk.

**Comment by anggrayudi** [comment]
Put logs wherever you construct `FileFullPath()` object. That will be really helpful.

**Comment by Shashank066** [comment]
The issue was empty path being passed to FileFullPath() in a specific case.
