### ISSUE TITLE
Error " java.lang.IllegalArgumentException: Request codes must be unique" similar to Issue #93 in 1.5.5

### ISSUE THREAD

**Issue by paoloasioli** [anggrayudi/SimpleStorage#133]
Library version: 1.5.5
OS version: [Android 13]
Device model: [Samsung a33x]

An issue identical to #93 is happening randomly in my development phone (but from published app).

**To Reproduce**
Not sure how to reproduce, I'm just restoring state as per examples... Seems to happen the first time I launch the app in a day or after some time since last launch...

**Stacktrace**
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4169)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4325)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:101)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2574)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.IllegalArgumentException: Request codes must be unique. File picker=3, Folder picker=0, Storage access=0, Create file=4
  at com.anggrayudi.storage.SimpleStorage.checkRequestCode (SimpleStorage.kt:538)
  at com.anggrayudi.storage.SimpleStorage.setRequestCodeFolderPicker (SimpleStorage.kt:73)
  at com.anggrayudi.storage.SimpleStorage.onRestoreInstanceState (SimpleStorage.kt:527)
  at com.anggrayudi.storage.SimpleStorageHelper.onRestoreInstanceState (SimpleStorageHelper.kt:380)
  at com.uglyicons.apps.android.emlreader.MainActivity.setupSimpleStorage (MainActivity.java:201)
  at com.uglyicons.apps.android.emlreader.MainActivity.onCreate (MainActivity.java:285)
  at android.app.Activity.performCreate (Activity.java:8591)
  at android.app.Activity.performCreate (Activity.java:8570)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1384)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4150)

**Comment by toumoudf** [comment]
SAME ISSUE java.lang.IllegalArgumentException: Request codes must be unique. File picker=3, Folder picker=0, Storage access=0, Create file=4
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)

FATAL EXCEPTION: main
Process: com.music_bu_neex.sn, PID: 17664
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.music_bu_neex.sn/com.music_bu_neex.sn.musiplayer_side.mainactivities.Music_Player}: java.lang.IllegalArgumentException: Request codes must be unique. File picker=3, Folder picker=0, Storage access=0, Create file=4
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6058)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5953)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:63)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6017)
	at android.app.ActivityThread.access$3500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2346)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.IllegalArgumentException: Request codes must be unique. File picker=3, Folder picker=0, Storage access=0, Create file=4
	at com.anggrayudi.storage.SimpleStorage.checkRequestCode(SimpleStorage.kt:538)
	at com.anggrayudi.storage.SimpleStorage.setRequestCodeFolderPicker(SimpleStorage.kt:73)
	at com.anggrayudi.storage.SimpleStorage.onRestoreInstanceState(SimpleStorage.kt:527)
	at com.anggrayudi.storage.SimpleStorage.<init>(SimpleStorage.kt:45)
	at com.music_bu_neex.sn.musiplayer_side.mainactivities.Music_Player.onCreate(Music_Player.java:171)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6058) 
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5953) 
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:63) 
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6017) 
	at android.app.ActivityThread.access$3500(ActivityThread.java:301) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2346) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:246) 
	at android.app.ActivityThread.main(ActivityThread.java:8653) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
