### ISSUE TITLE
Media is read-only

### ISSUE THREAD

**Issue by victorbnl** [anggrayudi/SimpleStorage#14]
Hello again! First, sorry for making a ton of issues

So I'm taking a file doing

```kotlin
// When a file is opened
storageHelper.onFileSelected = { _: Int, documentFile: DocumentFile ->
    openedFile = documentFile
    val content = getFileContent(this, documentFile)
    findViewById<EditText>(R.id.editTextTextMultilineContent).setText(content)
    toolbar.title = documentFile.name
}
// Ask for a file
storageHelper.openFilePicker(1, "text/*")
```

But when I try to edit it it says

`java.lang.IllegalArgumentException: Media is read-only`

<details>
<summary>Full error log</summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.victorb.androidtexteditor, PID: 16378
    java.lang.IllegalArgumentException: Media is read-only
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)
        at com.anggrayudi.storage.extension.UriUtils.openOutputStream(UriExt.kt:64)
        at com.anggrayudi.storage.file.DocumentFileUtils.openOutputStream(DocumentFileExt.kt:656)
        at com.anggrayudi.storage.file.DocumentFileUtils.openOutputStream$default(DocumentFileExt.kt:656)
        at com.victorb.androidtexteditor.FileUtilsKt.writeToFile(FileUtils.kt:23)
        at com.victorb.androidtexteditor.MainActivity.onOptionsItemSelected(MainActivity.kt:55)
        at android.app.Activity.onMenuItemSelected(Activity.java:4269)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7455)
        at android.view.View.performClickInternal(View.java:7432)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28313)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

It does it with all the files

I use Android 11, and strangely in a A11 emulator it works, it does that on my real device only

How can I be sure I'll be able to edit the file?

**Comment by anggrayudi** [comment]
Can you check `documentFile.isReadOnly` before opening the output stream?

**Comment by victorbnl** [comment]
Of course! It's `false` O.o

**Comment by anggrayudi** [comment]
It is strange. `documentFile.isReadOnly` should return `true` when that exception is thrown. Can you explain how to reproduce this bug in more detail, such as the file URI?

**Comment by victorbnl** [comment]
It works without problems too on my girlfriend's phone which is A10

File URI on emulator (where it works) : `content://com.android.externalstorage.documents/document/primary%3ADownload%2Flol.txt`

File URI on device (doesn't work) : `content://com.android.providers.media.documents/document/document%3A5277`

For the steps to reproduce I don't really know, there are many factors that could make it break. I'm rooted and use a custom ROM too so I guess it doesn't help

**Comment by anggrayudi** [comment]
Can you convert the read-only document file to `MediaFile` via `toMediaFile()` with version `0.5.2`?
```kotlin
val media = file.toMediaFile(context)
val isMyMedia = media.isMine
```
`isMyMedia` should true if it is editable.

**Comment by anggrayudi** [comment]
No activity for too long. Closed.
