### ISSUE TITLE
 Process: com.example.fileaccesssdk30, PID: 19939     android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)

### ISSUE THREAD

**Issue by HirenJodhani** [anggrayudi/SimpleStorage#63]
Library version: 0.13.0
OS version: [Android 11]
Device model: [EMUlater]

**Describe the bug**
[when copy file to (document file(TreeFolder)) then file successfully copy(image/video) but when copyFileToDownloadMedia then 
cresh app when media is video if image then copyFileToDownloadMedia successfully.]

**My Code**
```  
FileDescription fileDescription = new FileDescription(srcFile.getName(), "", srcFile.getType());
DocumentFileUtils.copyFileToDownloadMedia(srcFile, getApplicationContext(), fileDescription, new FileCallback() {
```

**Stacktrace**
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.example.fileaccesssdk30, PID: 19939
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:178)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
        at android.content.ContentResolver.insert(ContentResolver.java:2149)
        at android.content.ContentResolver.insert(ContentResolver.java:2111)
        at com.anggrayudi.storage.media.MediaStoreCompat.createMedia(MediaStoreCompat.kt:150)
        at com.anggrayudi.storage.media.MediaStoreCompat.createDownload(MediaStoreCompat.kt:33)
        at com.anggrayudi.storage.file.DocumentFileUtils.copyFileToMedia(DocumentFileExt.kt:2139)
        at com.anggrayudi.storage.file.DocumentFileUtils.copyFileToDownloadMedia(DocumentFileExt.kt:2154)
        at com.anggrayudi.storage.file.DocumentFileUtils.copyFileToDownloadMedia$default(DocumentFileExt.kt:2153)
        at com.anggrayudi.storage.file.DocumentFileUtils.copyFileToDownloadMedia(Unknown Source:28)
        at com.example.fileaccesssdk30.SimpleStorageSdk30CopyFolder$1$1.run(SimpleStorageSdk30CopyFolder.java:69)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by eclectice** [comment]
With API29+ as the target SDK version, I can get a quasi report like what you have had if I pass _MediaStore.VOLUME_EXTERNAL_ as the volume name in the `MediaStore.Files.getContentUri()` method when testing the codes on a non-Android10+ device as the _MediaStore.VOLUME_EXTERNAL_ is only supported on Android 10+.

```java
Uri uri = getContext().getContentResolver().insert(MediaStore.Files.getContentUri(MediaStore.VOLUME_EXTERNAL), contentValues);
```
```
Reason: no path was provided when inserting new file
Stack Trace:
android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
android.content.ContentResolver.insert(ContentResolver.java:1280)
```

**Comment by anggrayudi** [comment]
@eclectice explained very well. Thank you.

In your case @HirenJodhani, you're trying to create a new file which actually already exists in the current folder.
